version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.4
        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt"}}
            - run:
                name: Install Python dependencies and Test
                command: |
                    pip install --user -r requirements.txt
                    export PATH=$PATH:~/.local/bin
                    pytest tests
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt"}}
                paths:
                    -venv

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
