version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.4
        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt"}}
            - run:
                name: Install Python dependencies and Test
                command: |
                    pip install --user -r requirements.txt
                    export PATH=$PATH:~/.local/bin
                    sudo apt install gfortran
                    cd ./scatter/h2plus_pbar_pes/
                    f2py -c --fcompiler=gnu95 -m pes PES3.f  H2+pbar-bpm-pot-nn.f
                    mv pes.c* ../pes.so
                    cd ../../
                    pytest -v tests
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt"}}
                paths:
                    -venv

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
